[tool.black]
target-version = ["py38", "py39"]
color = true
skip_magic_trailing_comma = true
exclude = '''
/(
    | data
    | logo
    | logs
    | output
    | lightning_logs
    # Python
    | build
    | dist
    | \.cache
    | \.mypy_cache
    | \.pytest_cache
    |  __pycache__
    | .*\.egg-info
    # Git
    | \.git
    | \.github
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["csip"]
extend_skip = ["data", "logs", "lightning_logs", "output"]
skip_gitignore = true
color_output = true

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
exclude = "(build|data|dist|logs|output|lightning_logs)/"

# Strict
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[tool.pydocstyle]
convention = "google"
match_dir = "(csip)"

[tool.pytest.ini_options]
# Skip slow tests by default
addopts = "-m 'not slow'"
filterwarnings = [
    "ignore:.*Create unlinked descriptors is going to go away.*:DeprecationWarning",
    # https://github.com/tensorflow/tensorboard/pull/5138
    "ignore:.*is a deprecated alias for the builtin.*:DeprecationWarning",
]
markers = [
    "slow: marks tests as slow",
]
norecursedirs = [
    ".ipynb_checkpoints",
    "data",
    "logs",
    "lightning_logs",
    "output",
    "__pycache__",
]
testpaths = [
    "tests",
]