module:
    _target_: csip.models.ChangeDetectionModel
    model: FCSiamDiff
    backbone: resnet18
    num_channels: 3
    num_classes: 2
    learning_rate: 0.001
    weights: logs/pretrain-overhead-geopose/checkpoints/epoch=101-step=151061.ckpt
    freeze_encoder: True
    pad: True

datamodule:
    _target_: csip.datasets.OSCDDataModule
    root: /mnt/e/data/oscd/
    batch_size: 4
    num_workers: 4
    num_prefetch: 2
    val_split_pct: 0.2
    patch_size: 256

trainer:
    max_epochs: 100
    precision: 16
    gpus: 1
    log_every_n_steps: 2
